In [1]:
import numpy as np


In [2]:
print(np.sqrt(10))

3.1622776601683795


In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.array(range(1,100,10))

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [8]:
np.array(range(100,1,-10))

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [17]:
print("Hello")
x = [np.random.randint(1,6500) for i in range(1,100) ]
print("Hello 2")

Hello
Hello 2


In [18]:
np.sin(200)

np.float64(-0.8732972972139946)

In [19]:
np.std(2590)

np.float64(0.0)

In [20]:
np.exp(30)

np.float64(10686474581524.463)

In [21]:
np.sum([1,1,1,1,1,4,4,5,6,6,8,8,5,2,8,8])

np.int64(69)

In [23]:
print(np.min([10,60,50,20,1,5]))

1


In [24]:
print(np.amax([10,60,50,20,1,5]))

60


In [25]:
print(np.avarage([10,60,50,20,1,5]))

AttributeError: module 'numpy' has no attribute 'avarage'

In [26]:
print(np.average([10,60,50,20,1,5]))

24.333333333333332


In [27]:
print(np.sin([10,60,50,20,1,5]))

[-0.54402111 -0.30481062 -0.26237485  0.91294525  0.84147098 -0.95892427]


In [28]:
print(np.sqrt([10,60,50,20,1,5]))

[3.16227766 7.74596669 7.07106781 4.47213595 1.         2.23606798]


In [29]:
print(np.exp([10,60,50,20,1,5]))

[2.20264658e+04 1.14200739e+26 5.18470553e+21 4.85165195e+08
 2.71828183e+00 1.48413159e+02]


In [30]:
print(np.cos([10,60,50,20,1,5]))

[-0.83907153 -0.95241298  0.96496603  0.40808206  0.54030231  0.28366219]


In [31]:
print(np.log([10,60,50,20,1,5]))

[2.30258509 4.09434456 3.91202301 2.99573227 0.         1.60943791]


In [32]:
print(np.std([10,60,50,20,1,5]))

22.632326929023943


In [35]:
np.random.rand(20)

array([0.85178042, 0.57731257, 0.73239054, 0.24249826, 0.21279806,
       0.35888504, 0.42472243, 0.34182267, 0.27835654, 0.95806723,
       0.52936747, 0.79972468, 0.72978528, 0.7567309 , 0.02012095,
       0.43714613, 0.09828056, 0.26795907, 0.67264071, 0.4101597 ])

In [37]:
np.random.randint(1,100)

54