### install numpy

In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


### import numpy

In [2]:
import numpy as np

### check version of numpy

In [3]:
print(np.__version__)

2.3.3


#### To create numpy array we use array function

In [4]:
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


#### check  type of array 

In [ ]:
type(arr1)

## here we are checking type of list
x = [10,20,30,40]
type(x)

list

### creating 2d array

In [9]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

arr2

array([[1, 2, 3],
       [4, 5, 6]])

### creating 3d array

In [11]:
arr3 = np.array([
    [
        [1,2,3]
    ],
    [
        [4,5,6]
    ]
])
arr3

array([[[1, 2, 3]],

       [[4, 5, 6]]])

### check dimensions

In [12]:
arr3.ndim

3

### zeros function
 <b> this function create array of zeros</b>

In [20]:
zero_func = np.zeros(10,dtype=int)
zero_func

# we can also convert data type of zeros function

zero_func_float = zero_func.astype(float)
zero_func_float

## we can also create 2d arrays

zero_func_2d = np.zeros((4,4))
zero_func_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones function

**this function create arrays of 1**

In [21]:
ones_func = np.ones(10,dtype=int)
ones_func

# we can also convert data type of ones function

ones_func_float = ones_func.astype(float)
ones_func_float

## we can also create 2d arrays

ones_func_2d = np.ones((4,4))
ones_func_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### create diagonal matrix

In [ ]:
# 1st way
np.eye(5)

#2nd way
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### arange() function is used to create arrays from given range

In [28]:
np.arange(10)
np.arange(-20,20)
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

##### linspace() function in NumPy returns an array of evenly spaced numbers over a specified range. Unlike the range() function in Python that generates numbers with a specific step size. linspace() allows you to specify the total number of points you want in the array, and NumPy will calculate the spacing between the numbers automatically.



In [30]:
np.linspace(1,100,50,dtype=int)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

### shape() returns no. rows , cols and matrix

In [35]:
arr1 = np.arange((4,5))

TypeError: arange: scalar arguments expected instead of a tuple.

In [33]:
arr1.shape

(10,)

### Size function return size of array

In [34]:
arr1.size

10

### SLICING ARRAY

In [36]:
arr2 = np.array([10,20,30,40,50,60])

In [ ]:
print(arr2[-1])
print(arr1[1:3])


60
[11 21]


### 2d array slicing

In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
print(arr[0,1])
print(arr[1,1])
print(arr[:,1])
print(arr[1,:])

2
5
[2 5]
[4 5 6]


### mathematical functions

In [50]:
arr = np.arange(10,50,5)

In [58]:
print(arr)
print(sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(arr.itemsize)

[10 15 20 25 30 35 40 45]
220
27.5
27.5
11.4564392373896
131.25
8


### create empty array

In [60]:
np.empty((3,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [2.67022274e-307, 2.67019320e-306, 1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 2.29178686e-312]])

### random value 

In [62]:
random_arr = np.random.randint(10,100)
random_arr

59