In [2]:
import numpy as np

### indexing and slicing

In [6]:
arr=  np.arange(100,200,5).reshape((4,5))
arr

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [8]:
print(arr[1,3])

140


In [10]:
print(arr[1:3,1:4])

[[130 135 140]
 [155 160 165]]


### mathematical operations

In [12]:
arr1 = np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
arr2 = np.arange(100,200,5).reshape(4,5)
arr2

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [14]:
print(arr1+arr2)

[[100 106 112 118 124]
 [130 136 142 148 154]
 [160 166 172 178 184]
 [190 196 202 208 214]]


In [15]:
print(arr1-arr2)

[[-100 -104 -108 -112 -116]
 [-120 -124 -128 -132 -136]
 [-140 -144 -148 -152 -156]
 [-160 -164 -168 -172 -176]]


In [16]:
print(arr1*arr2)

[[   0  105  220  345  480]
 [ 625  780  945 1120 1305]
 [1500 1705 1920 2145 2380]
 [2625 2880 3145 3420 3705]]


In [18]:
print(arr1/arr2)

[[0.         0.00952381 0.01818182 0.02608696 0.03333333]
 [0.04       0.04615385 0.05185185 0.05714286 0.06206897]
 [0.06666667 0.07096774 0.075      0.07878788 0.08235294]
 [0.08571429 0.08888889 0.09189189 0.09473684 0.0974359 ]]


In [20]:
print(arr2+100)

[[200 205 210 215 220]
 [225 230 235 240 245]
 [250 255 260 265 270]
 [275 280 285 290 295]]


### statistical function (Mean, Median, Mode, etc...)

In [ ]:
print(np.mean(arr1))
print(np.median(arr1))
print(np.min(arr1))
print(np.max(arr1))




9.5
9.5
0
19
[[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736]
 [ 0.65028784 -0.28790332 -0.96139749 -0.75098725  0.14987721]]
[[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]
 [-0.83907153  0.0044257   0.84385396  0.90744678  0.13673722]
 [-0.75968791 -0.95765948 -0.27516334  0.66031671  0.98870462]]
[[      -inf 0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]
 [2.30258509 2.39789527 2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334 2.89037176 2.94443898]]


C:\Users\Mohammad Tofik\AppData\Local\Temp\ipykernel_22484\383074058.py:7: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr1))


In [28]:
print(np.sin(arr1))

[[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736]
 [ 0.65028784 -0.28790332 -0.96139749 -0.75098725  0.14987721]]


In [29]:
print(np.cos(arr1))

[[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]
 [-0.83907153  0.0044257   0.84385396  0.90744678  0.13673722]
 [-0.75968791 -0.95765948 -0.27516334  0.66031671  0.98870462]]


In [31]:
print(np.log(arr2))

[[4.60517019 4.65396035 4.70048037 4.74493213 4.78749174]
 [4.82831374 4.86753445 4.90527478 4.94164242 4.97673374]
 [5.01063529 5.04342512 5.07517382 5.10594547 5.13579844]
 [5.16478597 5.19295685 5.22035583 5.24702407 5.27299956]]
