In [ ]:
import numpy as np

## 1D Array

In [ ]:
arr =np.array([1,2,3,4,5])
print(arr)

#### to check weather array is 1D or not we use ndim() which meand number of dimensions 

In [ ]:
arr.ndim

## 2D Array

In [ ]:
arr1 =np.array([[1,2,3,4,5]])
print(arr1)
arr1.ndim
arr1.shape

## 3D Array

In [ ]:
arr3 =np.array(
    [
        [
            [1,2,3,4,5],
            [6,7,8,9,10],
        ],
        [
            [11,12,13,14,15],
            [16,17,18,19,20]
        ],
        [
            [21,22,23,24,25],
            [26,27,28,29,30]
        ]
    ]
    )
print(arr3)
arr3.ndim
arr3.shape

## some in built functions

In [ ]:
zero_function = np.zeros(10)
zero_function


## if we want to perform 2d array we hae to use this.add()

zero_function_2d_matrix = np.zeros((4,5))
# 4 -> no. of rows
# 5 -> no. of columns

print(zero_function_2d_matrix)
print(zero_function_2d_matrix.ndim)
print(zero_function_2d_matrix.shape)

#### to check data type of array we have dtype function

In [ ]:
print(zero_function_2d_matrix.dtype)
print(arr3.dtype)

#### convert data type we use astype(data type name)

In [ ]:
new_arr = zero_function_2d_matrix.astype(int)
print(new_arr)
print(new_arr.dtype)
print(new_arr.shape)

#### ones function

In [ ]:
ones_function = np.ones(10)
ones_function

In [ ]:
ones_function_2d_matrix = np.ones((5,5))
ones_function_2d_matrix

In [ ]:
ones_function_2d_matrix_int =  ones_function_2d_matrix.astype(int)
print(ones_function_2d_matrix_int)
print(ones_function_2d_matrix_int.dtype)
print(ones_function_2d_matrix_int.shape)

### Identity function. 
##### This function will create diagonal matrix. 

In [ ]:
identity_matrix = np.identity(10)
identity_matrix_int = identity_matrix.astype(int)
print(identity_matrix_int)

### copy array

In [ ]:
# 1st way is normal python

arr = np.ones((4,5),dtype=int)
copy_array = arr
copy_array

#2nd way using numpy

original_array = np.zeros((5,5))
copied_array = np.copy(original_array)
print(copied_array)

## Arrange Function

#### it will create arrays in range

In [45]:
# arrange_function_demo = np.arange(12)
# arrange_function_demo = np.arange(100,200)
arrange_function_demo = np.arange(100,200,10)
print(arrange_function_demo)

[100 110 120 130 140 150 160 170 180 190]


### reshape function

In [50]:
normal_array = np.arange(100,220,10)
new_2d_array = normal_array.reshape((4,3))
print(new_2d_array)

[[100 110 120]
 [130 140 150]
 [160 170 180]
 [190 200 210]]
